/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dell
 */
package online.examination.system;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import static online.examination.system.Homepage.display;

public class course extends javax.swing.JInternalFrame {
    DefaultComboBoxModel dm = new DefaultComboBoxModel();
    

    PreparedStatement pst = null;
    ResultSet rs = null;
   
    public course() {
        initComponents();
        update_cname();
        update_table();
        edit();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
    }
void update_cname()
{
   try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/online", "root", ""); 
    String sql = "select * from course";
    pst = con.prepareStatement(sql);
    rs = pst.executeQuery();
    while(rs.next())
    {
        cname.addItem(rs.getString("course_code"));
    }
    
    
    }catch(Exception e){} 
    
}
void update_table()
{
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/online", "root", ""); 
    String sql = "select * from course";
    pst = con.prepareStatement(sql);
    rs = pst.executeQuery();
    coursetable.setModel(DbUtils.resultSetToTableModel(rs));
    
    
    }catch(Exception e){}
}
void edit()
{
    
   // name.setEditable(false);
    //time.setEditable(false);
    //marks.setEditable(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        marks = new javax.swing.JTextField();
        coursecode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cname = new javax.swing.JComboBox();
        panel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursetable = new javax.swing.JTable();
        delete = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(950, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/add_30px.png"))); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 273, 124, 38));

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        panel1.setForeground(new java.awt.Color(204, 255, 204));
        panel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Course Name");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Total Marks");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Course Code");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panel1.add(jPanel2);
        jPanel2.setBounds(20, 60, 140, 140);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        marks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        coursecode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(marks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coursecode, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(coursecode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(marks, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        panel1.add(jPanel3);
        jPanel3.setBounds(180, 60, 240, 140);

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("ADD COURSE");
        panel1.add(jLabel6);
        jLabel6.setBounds(30, 10, 140, 50);

        cname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cname.setForeground(new java.awt.Color(0, 255, 0));
        cname.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cnamePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });
        panel1.add(cname);
        cname.setBounds(170, 30, 245, 23);

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, 434, 230));

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        panel2.setForeground(new java.awt.Color(204, 255, 204));
        panel2.setLayout(null);

        jLabel8.setBackground(new java.awt.Color(255, 0, 0));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("ALL COURSES");
        panel2.add(jLabel8);
        jLabel8.setBounds(30, 0, 140, 50);

        coursetable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        coursetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Courses", "Total Marks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(coursetable);

        panel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 50, 430, 490);

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 24, 476, 564));

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/delete_bin_30px.png"))); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 272, 127, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        if(name.getText().trim().isEmpty() || marks.getText().trim().isEmpty()|| coursecode.getText().trim().isEmpty()  )
              {
                  
                 JOptionPane.showMessageDialog(this, "Incomplete Details! Please check the details!");    
              }
             
            else{
        try{ 
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/online", "root", ""); 
                String sql = "insert into course values(?,?,?)";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setInt(1,Integer.parseInt(coursecode.getText()));
                ps.setString(2,name.getText());
                ps.setString(3,marks.getText());
                
                cname.addItem((String)name.getText());
                ps.executeUpdate();
                DefaultTableModel model = new DefaultTableModel();
                model.setRowCount(0);
                update_table();
                
                JOptionPane.showMessageDialog(this,"Course Added Successfully");
                
                coursecode.setText(null);
                name.setText(null);
                marks.setText(null);
                
                display.removeAll();
                STUDENTE s1 = new STUDENTE();
                course c1 = new course();
                display.add(s1).setVisible(true);
                display.removeAll();
                display.add(c1).setVisible(true);      
                
                
                
                }catch(Exception e){}
        }
                
    }//GEN-LAST:event_addActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void cnamePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cnamePopupMenuWillBecomeInvisible
        try{        
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/online", "root", "");
        String course = (String)cname.getSelectedItem();
        String sql = "Select * from course where course_name = ?";
        pst = con.prepareStatement(sql);
        pst.setString(1,course);
        rs= pst.executeQuery();
        if(rs.next())
        {
           String coursename = rs.getString("course_name");
           name.setText(coursename);
           
           String totalmarks = rs.getString("total_marks");
           marks.setText(totalmarks);
           
           
        }
        
        
        }catch(Exception e){}
    }//GEN-LAST:event_cnamePopupMenuWillBecomeInvisible

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
     try{     
         Class.forName("com.mysql.jdbc.Driver");
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/online", "root", ""); 
         int row = coursetable.getSelectedRow();
         String cell = coursetable.getModel().getValueAt(row,0).toString();
         String sql = "DELETE from course where course_code= "+cell;
         PreparedStatement p = con.prepareStatement(sql);
         int executeUpdate = p.executeUpdate();
         DefaultTableModel model = (DefaultTableModel)coursetable.getModel();
         model.setRowCount(0);
         update_table();
         update_cname();
           display.removeAll();
                STUDENTE s1 = new STUDENTE();
                course c1 = new course();
                display.add(s1).setVisible(true);
                display.removeAll();
                display.add(c1).setVisible(true);   
         //show_user();
         JOptionPane.showMessageDialog(this,"Item Deleted Successfully");
                
     }catch(Exception e){
     JOptionPane.showMessageDialog(this,e);}
     
       /*DefaultTableModel tb = (DefaultTableModel) coursetable.getModel();
       
       if(coursetable.getSelectedRowCount() == 1)
       {
           tb.removeRow(coursetable.getSelectedRow()) ;
           
       }else{
           if(coursetable.getRowCount()==0){
               JOptionPane.showMessageDialog(this,"this is empty");
               
           }
           else
           {
              JOptionPane.showMessageDialog(this,"please select single row for delete"); 
           }
       }*/
    }//GEN-LAST:event_deleteActionPerformed

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JComboBox cname;
    private javax.swing.JTextField coursecode;
    private javax.swing.JTable coursetable;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marks;
    javax.swing.JTextField name;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    // End of variables declaration//GEN-END:variables

   // private void show_user() {
  //      throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   // }
}
