/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.examination.system;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import static online.examination.system.Homepage.display;

/**
 *
 * @author Dell
 */
public class exam extends javax.swing.JInternalFrame {

    /**
     * Creates new form exam
     */
    public exam() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        schemes = new javax.swing.JTextField();
        datee = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(950, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel1.setText("exam DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton3.setBackground(new java.awt.Color(51, 255, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/icons8_save_32.png"))); // NOI18N
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(338, 379, 157, 45);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Schemes:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 310, 100, 22);

        schemes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        schemes.setToolTipText("Alloted marks per question");
        jPanel1.add(schemes);
        schemes.setBounds(263, 303, 410, 30);

        datee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(datee);
        datee.setBounds(263, 255, 410, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Date:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 260, 100, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Exam Name:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(110, 220, 100, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Exam No:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 180, 100, 22);

        no.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(no);
        no.setBounds(263, 170, 410, 30);

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(name);
        name.setBounds(263, 213, 410, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Time:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 130, 59, 22);

        time.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        jPanel1.add(time);
        time.setBounds(264, 122, 410, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Exam Code:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 80, 120, 22);

        code.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });
        jPanel1.add(code);
        code.setBounds(264, 74, 410, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 800, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

                    if(code.getText().trim().isEmpty() || name.getText().trim().isEmpty() || time.getText().trim().isEmpty() || no.getText().trim().isEmpty() || datee.getText().trim().isEmpty() || schemes.getText().trim().isEmpty()  )
              {
                  
                 JOptionPane.showMessageDialog(this, "Incomplete Details! Please check the details!");    
              }
             
                    else{
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/online", "root", "");
            String sql = "insert into exam values(?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1,Integer.parseInt( code.getText()));

            ps.setInt(2, Integer.parseInt(time.getText()));
            ps.setInt(3, Integer.parseInt(no.getText()));
            ps.setString(4, name.getText());
            ps.setString(5, datee.getText());
        
           
            
            ps.setString(6,schemes.getText());
   
         

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Exam Details Added Successfully");
            
       code.setText(""); 
       time.setText("");
       no.setText("");
       name.setText("");
        datee.setText("");
       schemes.setText("");
   
       
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Something went wrong!");
        }}
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code;
    private javax.swing.JTextField datee;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField no;
    private javax.swing.JTextField schemes;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
