/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dell
 */
package online.examination.system;
import java.awt.Color;
import static java.lang.Thread.sleep;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class Homepage extends javax.swing.JFrame {
  ImageIcon icon;
    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
        icon = new ImageIcon("image/logo.png");
        setIconImage(icon.getImage());

        clock();
        Date obj = new Date();
        String date = obj.toString();
    }

void clock()
    {
               Thread clk = new Thread() 
        {
            
            @Override
            public void run()
            {
                for(;;)
                {
                  
                  DateFormat dateformat = new SimpleDateFormat("dd-MMM-YYYY hh:mm aa");
                  String datestring = dateformat.format(new Date()).toString();
                  
                  //Date timedate = new Date();
                   //Calendar cal = Calendar.getInstance();   
                  time.setText(datestring);
                    try
                    {
                        sleep(1000);
                        
                    }catch(Exception e){}
                    
                }
            }
            
        };
      clk.start();    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        exam = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        accounts = new javax.swing.JButton();
        questions = new javax.swing.JButton();
        courses = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        profile = new javax.swing.JButton();
        result = new javax.swing.JButton();
        aboutus = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        display = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, -1, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Online Examination System");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/minimise icon.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, -1, 40));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/close.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 30, 40));

        time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("TIME");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1250, 40));

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setLayout(null);

        exam.setBackground(new java.awt.Color(255, 0, 0));
        exam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        exam.setForeground(new java.awt.Color(255, 255, 255));
        exam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/icons8-exam-30.png"))); // NOI18N
        exam.setText("Exam");
        exam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examActionPerformed(evt);
            }
        });
        jPanel2.add(exam);
        exam.setBounds(50, 440, 220, 40);
        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, -40, 510, 30);

        accounts.setBackground(new java.awt.Color(255, 0, 0));
        accounts.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        accounts.setForeground(new java.awt.Color(255, 255, 255));
        accounts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/icons8-user-group-30.png"))); // NOI18N
        accounts.setText("Accounts");
        accounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountsActionPerformed(evt);
            }
        });
        jPanel2.add(accounts);
        accounts.setBounds(50, 540, 220, 40);

        questions.setBackground(new java.awt.Color(255, 0, 0));
        questions.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        questions.setForeground(new java.awt.Color(255, 255, 255));
        questions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/icons8-faq-30.png"))); // NOI18N
        questions.setText("Questions");
        questions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionsActionPerformed(evt);
            }
        });
        jPanel2.add(questions);
        questions.setBounds(50, 490, 220, 40);

        courses.setBackground(new java.awt.Color(255, 0, 0));
        courses.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        courses.setForeground(new java.awt.Color(255, 255, 255));
        courses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/icons8-course-30.png"))); // NOI18N
        courses.setText("Courses");
        courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursesActionPerformed(evt);
            }
        });
        jPanel2.add(courses);
        courses.setBounds(50, 390, 220, 40);
        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, -40, 60, 30);
        jPanel2.add(jPanel5);
        jPanel5.setBounds(10, -40, 30, 40);

        profile.setBackground(new java.awt.Color(255, 0, 0));
        profile.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/profilepic.png"))); // NOI18N
        profile.setText("Profile");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        jPanel2.add(profile);
        profile.setBounds(50, 340, 220, 40);

        result.setBackground(new java.awt.Color(255, 0, 0));
        result.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        result.setForeground(new java.awt.Color(255, 255, 255));
        result.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/icons8-leaderboard-30.png"))); // NOI18N
        result.setText("Result");
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });
        jPanel2.add(result);
        result.setBounds(50, 590, 220, 40);

        aboutus.setBackground(new java.awt.Color(255, 0, 0));
        aboutus.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        aboutus.setForeground(new java.awt.Color(255, 255, 255));
        aboutus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/icons8-more-info-30.png"))); // NOI18N
        aboutus.setText("AboutUs");
        aboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutusActionPerformed(evt);
            }
        });
        jPanel2.add(aboutus);
        aboutus.setBounds(50, 640, 220, 40);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 290, 780));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setText("ADMIN PANEL");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 210, -1));

        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/logout.png"))); // NOI18N
        jLabel6.setToolTipText("CLICK HERE FOR LOG OUT");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 950, 90));

        display.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/bhokandi.PNG"))); // NOI18N

        javax.swing.GroupLayout displayLayout = new javax.swing.GroupLayout(display);
        display.setLayout(displayLayout);
        displayLayout.setHorizontalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );
        displayLayout.setVerticalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 950, 680));

        setSize(new java.awt.Dimension(1238, 811));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int x,y;
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x,yy-y);

    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getX();
        y = evt.getY();

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void examActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examActionPerformed
        profile.setBackground(Color.red);
        courses.setBackground(Color.red);
        exam.setBackground(Color.black);
        questions.setBackground(Color.red);
        accounts.setBackground(Color.red);
        result.setBackground(Color.red);
          aboutus.setBackground(Color.red);
        display.removeAll();
        exam_panel p1=new exam_panel();
        display.add(p1).setVisible(true);
        exam_panel f = new exam_panel();
    }//GEN-LAST:event_examActionPerformed

    private void accountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountsActionPerformed
        profile.setBackground(Color.red);
        courses.setBackground(Color.red);
        exam.setBackground(Color.red);
        questions.setBackground(Color.red);
        accounts.setBackground(Color.black);
        result.setBackground(Color.red);
        aboutus.setBackground(Color.red);
        display.removeAll();
        accounts p1=new accounts();
        display.add(p1).setVisible(true);
        accounts f = new accounts();        // TODO add your handling code here:
    }//GEN-LAST:event_accountsActionPerformed

    private void questionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionsActionPerformed
        profile.setBackground(Color.red);
        courses.setBackground(Color.red);
        exam.setBackground(Color.red);
        questions.setBackground(Color.black);
        accounts.setBackground(Color.red);
        result.setBackground(Color.red);
       aboutus.setBackground(Color.red);
        display.removeAll();
        questions p1=new questions();
        display.add(p1).setVisible(true);
        // accounts f = new accounts();
    }//GEN-LAST:event_questionsActionPerformed

    private void coursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursesActionPerformed
        profile.setBackground(Color.red);
        courses.setBackground(Color.black);
        exam.setBackground(Color.red);
        questions.setBackground(Color.red);
        accounts.setBackground(Color.red);
        result.setBackground(Color.red);
       aboutus.setBackground(Color.red);
        display.removeAll();
        course p1=new course();
        display.add(p1).setVisible(true);

    }//GEN-LAST:event_coursesActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        profile.setBackground(Color.black);
        courses.setBackground(Color.red);
        exam.setBackground(Color.red);
        questions.setBackground(Color.red);
        accounts.setBackground(Color.red);
        result.setBackground(Color.red);
        aboutus.setBackground(Color.red);
        display.removeAll();
        profile p1=new profile();
        display.add(p1).setVisible(true);
        profile f = new profile();       // TODO add your handling code here:
    }//GEN-LAST:event_profileActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    this.setState(ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
    int resp =JOptionPane.showConfirmDialog(this,"Do you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE); 
if(resp == JOptionPane.YES_OPTION)
{
  System.exit(0);
   
}
   else if ( resp == JOptionPane.NO_OPTION)
      {
         JOptionPane.getRootFrame().dispose();
          this.setVisible(true);
      }
                 // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
this.setVisible(false);
new loginn().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        profile.setBackground(Color.red);
        courses.setBackground(Color.red);
        exam.setBackground(Color.red);
        questions.setBackground(Color.red);
        accounts.setBackground(Color.red);
        result.setBackground(Color.black);
        aboutus.setBackground(Color.red);
        display.removeAll();
        result p1=new result();
        display.add(p1).setVisible(true);
        result f = new result();
        
    }//GEN-LAST:event_resultActionPerformed

    private void aboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutusActionPerformed
        profile.setBackground(Color.red);
        courses.setBackground(Color.red);
        exam.setBackground(Color.red);
        questions.setBackground(Color.red);
        accounts.setBackground(Color.red);
        result.setBackground(Color.red);
        aboutus.setBackground(Color.black);
        display.removeAll();
        aboutus p1=new aboutus();
        display.add(p1).setVisible(true);
        aboutus f = new aboutus();        // TODO add your handling code here:
    }//GEN-LAST:event_aboutusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutus;
    private javax.swing.JButton accounts;
    private javax.swing.JButton courses;
    public static javax.swing.JPanel display;
    private javax.swing.JButton exam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JButton profile;
    private javax.swing.JButton questions;
    private javax.swing.JButton result;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
