/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.examination.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



public class loginn extends javax.swing.JFrame {
    ImageIcon icon;
  PreparedStatement pst = null;
    ResultSet rs = null;
    String id;

    
    public loginn() {
        initComponents();
         icon = new ImageIcon("image/logo.png");
        setIconImage(icon.getImage());
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adminlogin = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        studentlogin = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Online Examination System");
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        adminlogin.setBackground(new java.awt.Color(255, 0, 0));
        adminlogin.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        adminlogin.setForeground(new java.awt.Color(255, 255, 255));
        adminlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/administrator_male_30px.png"))); // NOI18N
        adminlogin.setText("Admin Login");
        adminlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminloginActionPerformed(evt);
            }
        });
        jPanel1.add(adminlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 320, -1, 40));

        txtUser.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtUser.setToolTipText("ENTER YOUR USERNAME HERE");
        txtUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 230, 40));

        studentlogin.setBackground(new java.awt.Color(255, 0, 0));
        studentlogin.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        studentlogin.setForeground(new java.awt.Color(255, 255, 255));
        studentlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/student_male_30px.png"))); // NOI18N
        studentlogin.setText("Student Login");
        studentlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentloginActionPerformed(evt);
            }
        });
        jPanel1.add(studentlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 160, 40));

        txtPass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtPass.setToolTipText("ENTER YOUR PASSWORD HERE");
        txtPass.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 230, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setText("Username:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/user.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 60, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/forgot.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/forgot.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/icons8-close-window-30.png"))); // NOI18N
        jLabel7.setToolTipText("CLICK HERE TO CLOSE");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 430);

        setSize(new java.awt.Dimension(630, 432));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void adminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminloginActionPerformed
            if(txtUser.getText().trim().isEmpty() || txtPass.getText().trim().isEmpty()  )
              {
                  
                 JOptionPane.showMessageDialog(this, "Incomplete Details! Please check the details!");    
              }
             
            else{
        try 
    {
        
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/online", "root", "");
            pst = con.prepareStatement("SELECT * FROM login WHERE username = ? AND password=  ?");
            pst.setString(1, txtUser.getText());
            pst.setString(2, txtPass.getText());
            id = txtUser.getText();
            rs = pst.executeQuery();
           
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this,"Login Successfull");
                id = txtUser.getText();
                setVisible(false);
                Homepage mf = new Homepage();
                mf.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Username Or Password Are Invalid");
            }
    } 
    catch(ClassNotFoundException | NumberFormatException | SQLException e)
            {
                JOptionPane.showMessageDialog(this,"Something went wrong!");
            } 
            }
    }//GEN-LAST:event_adminloginActionPerformed

    private void studentloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentloginActionPerformed
                if(txtUser.getText().trim().isEmpty() || txtPass.getText().trim().isEmpty()  )
              {
                  
                 JOptionPane.showMessageDialog(this, "Incomplete Details! Please check the details!");    
              }
             
            else{
        
        try 
    {
        
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/online", "root", "");
            pst = con.prepareStatement("SELECT * FROM student WHERE enrollment_no = ? AND enrollment_no=  ?");
            pst.setString(1, txtUser.getText());
            
            pst.setString(2, txtPass.getText());
            id = txtUser.getText();
            rs = pst.executeQuery();
           
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this,"Login Successfull");
                id = txtUser.getText();
                setVisible(false);
                stupanel mf = new stupanel();
                mf.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Username Or Password Are Invalid");
            }
    } 
    catch(ClassNotFoundException | NumberFormatException | SQLException e)
            {
                JOptionPane.showMessageDialog(this,"Something went wrong!");
            }  
                }
    }//GEN-LAST:event_studentloginActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton studentlogin;
    private javax.swing.JPasswordField txtPass;
    public static javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
