package online.examination.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import static online.examination.system.Homepage.display;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dell
 */
public class questions extends javax.swing.JInternalFrame {

    
    PreparedStatement pst = null;
    ResultSet rs = null;
    public questions() {
        initComponents();
        update_cnamee();
        update_cnameee();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }
    
    
    void update_cnamee()
{
   try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/online", "root", ""); 
    String sql = "select * from exam";
    pst = con.prepareStatement(sql);
    rs = pst.executeQuery();
    while(rs.next())
    {
        comque3.addItem(rs.getString("code"));
    
    }
    
    
    }catch(Exception e){} 
    
}
       void update_cnameee()
{
   try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/online", "root", ""); 
    String sql = "select * from course";
    pst = con.prepareStatement(sql);
    rs = pst.executeQuery();
    while(rs.next())
    {
        comque.addItem(rs.getString("course_name"));
    }
    
    
    }catch(Exception e){} 
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        comque3 = new javax.swing.JComboBox();
        add = new javax.swing.JButton();
        a4 = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        question = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        a6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comque = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        a5 = new javax.swing.JTextField();
        correct = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(950, 700));

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        panel1.setForeground(new java.awt.Color(204, 255, 204));
        panel1.setLayout(null);

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setText("Show All Questions");
        panel1.add(jLabel6);
        jLabel6.setBounds(60, 30, 170, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/eye_30px.png"))); // NOI18N
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel1.add(jButton1);
        jButton1.setBounds(60, 80, 160, 40);

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 0, 0));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Add New Question");
        panel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 200, 50));

        comque3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        comque3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comque3ItemStateChanged(evt);
            }
        });
        comque3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comque3ActionPerformed(evt);
            }
        });
        panel2.add(comque3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 130, 40));

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/add_30px.png"))); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        panel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 170, 40));

        a4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });
        panel2.add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 180, 34));

        a1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        panel2.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 180, 34));

        a2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        panel2.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 180, 34));

        a3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        panel2.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 180, 34));

        question.setColumns(20);
        question.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        question.setRows(5);
        jScrollPane1.setViewportView(question);

        panel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 430, 140));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Answers:");
        panel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 100, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Correct Answer:");
        panel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 120, 30));

        a6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        panel2.add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 180, 34));

        jLabel1.setText("F");
        panel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 10, -1));

        jLabel3.setText("A");
        panel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 10, -1));

        jLabel4.setText("C");
        panel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 10, -1));

        jLabel5.setText("B");
        panel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 10, -1));

        jLabel9.setText("D");
        panel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 10, -1));

        jLabel13.setText("E");
        panel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 10, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Select course:");
        panel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Exam Code:");
        panel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 100, 40));

        comque.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        panel2.add(comque, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 120, 40));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Questions:");
        panel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, 30));

        a5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });
        panel2.add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 180, 34));

        correct.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        correct.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E", "F" }));
        panel2.add(correct, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        display.removeAll();
        questionbank q1 = new questionbank();
        display.add(q1).setVisible(true);        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

                    if(question.getText().trim().isEmpty() || a1.getText().trim().isEmpty() || a2.getText().trim().isEmpty() || a3.getText().trim().isEmpty() || a4.getText().trim().isEmpty() || a5.getText().trim().isEmpty() || a6.getText().trim().isEmpty() )
              {
                  
                 JOptionPane.showMessageDialog(this, "Incomplete Details! Please check the details!");    
              }
             

                    else{
        try
        {   
            String sql = "insert into question values("+null+",?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps = db.mycon().prepareStatement(sql);
            
           String course ;
           course = comque3.getSelectedItem().toString();
           ps.setString(1,course);
           
           String code ;
           code = comque.getSelectedItem().toString();
           ps.setString(2,code);
           
           
           
           //ps.setString(3, qno.getText());
           ps.setString(3,question.getText());
           ps.setString(4, a1.getText());
           ps.setString(5, a2.getText());
           ps.setString(6, a3.getText());
           ps.setString(7,a4.getText());
           ps.setString(8,a5.getText());
           ps.setString(9,a6.getText());
           
           String corr ;
           corr = correct.getSelectedItem().toString();
           ps.setString(10,corr);
            
            

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Question Added Successfully");
       //qno.setText(""); 
            question.setText("");
            a1.setText("");
            a2.setText("");
            a3.setText("");
            a4.setText("");
            a5.setText("");
            a6.setText("");
        }
        catch(NumberFormatException | SQLException e)
        {

        }   
        /*  try{  
         
         Statement run_query=db.mycon().createStatement();
     String query="INSERT INTO question VALUES("+null+","+comque.getSelectedItem().toString()+","+comque3.getSelectedItem().toString()+",'"+question.getText()+"','"+a1.getText()+"','"+a2.getText()+"','"+a3.getText()+"','"+a4.getText()+"','"+a5.getText()+"','"+a6.getText()+"','"+correct.getText()+"')";
         run_query.executeUpdate(query);
        question.setText("");
        a1.setText("");
        a2.setText("");
        a3.setText("");
        a4.setText("");
        a5.setText("");
        a6.setText("");
        correct.setText("");
     }
     catch(Exception e){
    
         JOptionPane.showMessageDialog(null,"You may have error in statment try code...!");
    } */
                    }
    }//GEN-LAST:event_addActionPerformed

    private void comque3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comque3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comque3ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a4ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    private void comque3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comque3ItemStateChanged
 /*    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/online", "root", ""); 
    String sql = "select * from exam where code='"+comque3.getSelectedItem()+"'";
    
    pst = con.prepareStatement(sql);
    rs = pst.executeQuery();
    while(rs.next())
    {
        
        
        
    }
    
    
    }catch(Exception e){} */
    }//GEN-LAST:event_comque3ItemStateChanged

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField a5;
    private javax.swing.JTextField a6;
    private javax.swing.JButton add;
    private javax.swing.JComboBox comque;
    private javax.swing.JComboBox comque3;
    private javax.swing.JComboBox correct;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JTextArea question;
    // End of variables declaration//GEN-END:variables
}
