package online.examination.system;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dell
 */

public class STUDENTE extends javax.swing.JInternalFrame {

    /**
     * Creates new form STUDENTE
     */
    public STUDENTE() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        seat = new javax.swing.JTextField();
        mno = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        name = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        registor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        enroll = new javax.swing.JTextField();
        branch = new javax.swing.JComboBox();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Enrollment No: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 189, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Student Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 231, -1, -1));

        seat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(seat, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 186, 173, -1));

        mno.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(mno, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 271, 512, -1));

        email.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 344, 512, -1));

        address.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 379, 512, -1));

        fname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 414, 512, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Mobile No:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 271, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Email ID:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 346, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Gender:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 311, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Address:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 382, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Father's Name:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 417, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Branch:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 452, -1, -1));

        male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        male.setText("Male");
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 308, -1, -1));

        female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        female.setText("Female");
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 308, -1, -1));

        name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 227, 512, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registor.setBackground(new java.awt.Color(0, 255, 0));
        registor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        registor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/icons8_save_32.png"))); // NOI18N
        registor.setText("Register Now");
        registor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registorActionPerformed(evt);
            }
        });
        jPanel1.add(registor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 180, 50));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel1.setText("STUDENT REGISTRATION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Exam Seat No:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        enroll.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(enroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 210, -1));

        branch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CO", "CR", "EX", "IF" }));
        jPanel1.add(branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 70, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registorActionPerformed
            if(enroll.getText().trim().isEmpty() || seat.getText().trim().isEmpty() || name.getText().trim().isEmpty() || mno.getText().trim().isEmpty() || email.getText().trim().isEmpty() ||address.getText().trim().isEmpty() || male.getText().trim().isEmpty() || female.getText().trim().isEmpty() || fname.getText().trim().isEmpty() )
              {
                  
                 JOptionPane.showMessageDialog(this, "Incomplete Details! Please check the details!");    
              }
             
            else{
        try
        {
            
            String sql = "insert into student values(?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps = db.mycon().prepareStatement(sql);
            ps.setString(1,enroll.getText());

            ps.setString(2, seat.getText());
            ps.setString(3, name.getText());
            ps.setString(5,mno.getText());
          
             String gender;
               if(male.isSelected())
               {
                   gender = male.getText();
                   
               }
               else
               {
                   gender = female.getText();
               }
               ps.setString(6,gender);

           
            
            ps.setString(4,email.getText());
            ps.setString(7,address.getText());
            ps.setString(8,fname.getText());
           String branches ;
           branches = branch.getSelectedItem().toString();
       
            ps.setString(9,branches);
         

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Student Details Added Successfully");
            
       enroll.setText(""); 
       seat.setText("");
       name.setText("");
      mno.setText("");
       
       email.setText("");
       address.setText("");
       fname.setText("");
       
       
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Something went wrong!");
        }  }      // TODO add your handling code here:
    }//GEN-LAST:event_registorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JComboBox branch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField email;
    private javax.swing.JTextField enroll;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mno;
    private javax.swing.JTextField name;
    private javax.swing.JButton registor;
    private javax.swing.JTextField seat;
    // End of variables declaration//GEN-END:variables
}
