/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.examination.system;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.Timer;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.JOptionPane;
import static online.examination.system.Exampanel.*;
import static online.examination.system.student_profile.enrollment;
/**
 *
 * @author Dell
 */

public class studentexam extends javax.swing.JInternalFrame {
    private Object dbconnection;
       Connection conn;
       public  int count = 0;
       String add1,a1,add2;
    
       int temp = 2;
       
       //Timer cha declaration start
       int m ,s=00;
       Timer timer;
       boolean flag =true;
       //timer cha declaration end
       
       
       
       public String hold=null;
  
 
  
    public studentexam() throws SQLException {
        
        
       initComponents();
      
       timesathifunction();
       mehnat.setVisible(false);
       //String sss = c.getSelectedValue().toString();
       //mehnat.setText(sss);
      
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        
          try {
                conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/online","root","");
                Statement run_query=conn.createStatement();
                String query="SELECT course_name FROM course";
               ResultSet rs;      
               rs=run_query.executeQuery(query);

               DefaultListModel ob=new DefaultListModel();
               while(rs.next()){

                   query=rs.getString("course_name");
            ob.addElement(query);
               }
             c.setModel(ob);


        
        
    } catch (SQLException ex) {
        
        JOptionPane.showMessageDialog(null,"Plz check your connection ...!");
    
    }
   
    
        
    }
    
    
   // Ha code timer karita aahe 
            void timesathifunction()
            {
               try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/online", "root", ""); 
                String sql = "select * from exam";
                   PreparedStatement pst = con.prepareStatement(sql);
                   ResultSet rs = pst.executeQuery();
                while(rs.next())
                {
                    m= Integer.parseInt(rs.getString("time"));

                }


                }catch(Exception e){} 

            }
            
    // ithe timer sampla aahe
            
            
           
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        c = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mehnat = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        panel1.setForeground(new java.awt.Color(204, 255, 204));
        panel1.setPreferredSize(new java.awt.Dimension(950, 700));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/play_30px.png"))); // NOI18N
        jButton1.setText("Start Exam");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 140, 40));

        c.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        c.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                cValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(c);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 230, 110));

        panel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 310, 190));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Best of Luck for your exam!");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 630, -1, -1));

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel5.setText("Select Course To Take Exam");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 280, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel2.setText("Instructions:");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("1) All questions are compulsary.");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("3) Do not foget your Enrollment number and your password.");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 580, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("4) Use of Internet is totally prohibited. ");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("2) Once answer is submitted it can't be changed.");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 490, 20));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("6) You can see the time left on the upper right corner.  ");
        panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, 20));
        panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("5) Do not carry any electronic devices like mobile phones, pagers and any other gadgets.  ");
        panel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, 20));

        mehnat.setText("jLabel4");
        panel1.add(mehnat, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
         // TODO add your handling code here selecting item of list:
          
          String selected=c.getSelectedValue().toString();
       // JOptionPane.showMessageDialog(null,selected);
       
         //this will hold value 
    try{    
        Statement run_query=db.mycon().createStatement();
        String query="SELECT * FROM exam WHERE name='"+selected+"'";
        System.out.println(selected);
        ResultSet rs;      
        rs=run_query.executeQuery(query);

      
       while(rs.next()){
             hold=  rs.getString("code");
            System.out.println(hold);
            mehnat.setText(rs.getString("name"));
           
       }
       
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    
    }
    try
    {
        String sql2 = "SELECT * FROM result where enrollment_no= '"+enrollment.getText().toString()+" '";
        Statement s = db.mycon().createStatement();
        ResultSet rs = s.executeQuery(sql2);
        while(rs.next())
        {
            String eg = rs.getString("enrollment_no");
            if(eg.equals(enrollment.getText()))
            {
                JOptionPane.showMessageDialog(null,"You Already Appeared for Same Exam..!","Warning",JOptionPane.WARNING_MESSAGE);
                System.exit(0);
            }
            
        }
    }catch(Exception e){}
    
  
   
  
       
        Exampanel obj = new Exampanel();
        stupanel ob2 = new stupanel();
       obj.setValue(hold);
       obj.setVisible(true);
       //ob2.setVisible(false);
     
      
      
       
        
       
          timer = new Timer(1000, new ActionListener(){
              
              public void actionPerformed(ActionEvent e) {
                  
                  if (s==0){
                      s=60;
                      m--;
                  }
                  if(m<0){
                      JOptionPane.showMessageDialog(rootPane,"Timesup","Stopped",0);
                      m=0;s=0;
                      timer.stop();
                  }else{
                 
                 s--;
                 if(s<10){
                 sec.setText("0"+s);
                 flag=false;
                 
                 }
                 if (m<10){
                     min.setText("0"+m);
                     if(s<10)
                         sec.setText("0"+s);
                         else
                         sec.setText(""+s);
                     flag=false;
                 }
                 if(flag){
                     
                 
                 min.setText(""+m);
                 sec.setText(""+s);
                 
              }}}
          });
          timer.start();
        cmin.setVisible(false);
        csec.setVisible(false);
        start.setVisible(false);
        stop.setVisible(false);
               
        this .hide();
    this.dispose();
      ob2.dispose();
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_cValueChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList c;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel mehnat;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables

    
}
