/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dell
 */
package online.examination.system;

import java.awt.Color;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static online.examination.system.loginn.txtUser;
import static online.examination.system.student_profile.add;
import static online.examination.system.student_profile.branch;
import static online.examination.system.student_profile.email;
import static online.examination.system.student_profile.enrollment;
import static online.examination.system.student_profile.father;
import static online.examination.system.student_profile.gender;
import static online.examination.system.student_profile.mob;
import static online.examination.system.student_profile.studname;
import static online.examination.system.student_profile.number;

public class stupanel extends javax.swing.JFrame {
    ImageIcon icon;
   String idd = txtUser.getText(); 
    public stupanel() {
        initComponents();
         icon = new ImageIcon("image/logo.png");
        setIconImage(icon.getImage());
        clock();
        Date obj = new Date();
        String date = obj.toString();
    }
    void clock()
    {
               Thread clk = new Thread() 
        {
            
            @Override
            public void run()
            {
                for(;;)
                {
                  
                  DateFormat dateformat = new SimpleDateFormat("dd-MMM-YYYY hh:mm aa");
                  String datestring = dateformat.format(new Date()).toString();
                  
                  //Date timedate = new Date();
                   //Calendar cal = Calendar.getInstance();   
                  time.setText(datestring);
                    try
                    {
                        sleep(1000);
                        
                    }catch(Exception e){}
                    
                }
            }
            
        };
      clk.start();    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        profile = new javax.swing.JButton();
        exam = new javax.swing.JButton();
        aboutus = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        result = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        display = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Online Examination System");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/minimise icon.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, -1, 40));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/close.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 30, 40));

        time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("TIME");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, -1));

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setLayout(null);
        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, -40, 510, 30);
        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, -40, 60, 30);
        jPanel2.add(jPanel5);
        jPanel5.setBounds(10, -40, 30, 40);

        profile.setBackground(new java.awt.Color(255, 0, 0));
        profile.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/profilepic.png"))); // NOI18N
        profile.setText("Profile");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        jPanel2.add(profile);
        profile.setBounds(50, 390, 180, 40);

        exam.setBackground(new java.awt.Color(255, 0, 0));
        exam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        exam.setForeground(new java.awt.Color(255, 255, 255));
        exam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/icons8-exam-30.png"))); // NOI18N
        exam.setText("Exam");
        exam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examActionPerformed(evt);
            }
        });
        jPanel2.add(exam);
        exam.setBounds(50, 440, 180, 40);

        aboutus.setBackground(new java.awt.Color(255, 0, 0));
        aboutus.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        aboutus.setForeground(new java.awt.Color(255, 255, 255));
        aboutus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/icons8-more-info-30.png"))); // NOI18N
        aboutus.setText("AboutUs");
        aboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutusActionPerformed(evt);
            }
        });
        jPanel2.add(aboutus);
        aboutus.setBounds(50, 490, 180, 40);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 40, 300, 780));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setText("STUDENT PANEL");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 240, -1));

        result.setBackground(new java.awt.Color(255, 0, 0));
        result.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        result.setForeground(new java.awt.Color(255, 255, 255));
        result.setText("Result");
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });
        jPanel6.add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(-830, 430, 180, 40));

        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/logout.png"))); // NOI18N
        jLabel6.setToolTipText("CLICK HERE FOR LOG OUT");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 40, 950, 90));

        display.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/examination/system/bhokandi.PNG"))); // NOI18N

        javax.swing.GroupLayout displayLayout = new javax.swing.GroupLayout(display);
        display.setLayout(displayLayout);
        displayLayout.setHorizontalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        displayLayout.setVerticalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );

        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 127, 940, 690));

        setSize(new java.awt.Dimension(1234, 812));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int x,y;
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x,yy-y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getX();
        y = evt.getY();

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        profile.setBackground(Color.black);
     
        exam.setBackground(Color.red);
       
        aboutus.setBackground(Color.red);


        display.removeAll();
        student_profile p1=new student_profile();
        display.add(p1).setVisible(true);
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/online", "root", "");
            String sql = "select * from student where enrollment_no = "+(String)idd;

            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next())
            {

                String s1 = rs.getString("enrollment_no");
                enrollment.setText(s1);
                String s2 = rs.getString("exam_seat");
                number.setText(s2);
                String s3 = rs.getString("student_name");
                studname.setText(s3); 
                String s4 = rs.getString("email_id");
                email.setText(s4);
                String s5 = rs.getString("mobile_no");
                mob.setText(s5);
                String s6 = rs.getString("gender");
                gender.setText(s6);
                String s7 = rs.getString("address");
                add.setText(s7);
                String s8 = rs.getString("father_name");
                father.setText(s8);
                String s9 = rs.getString("branch");
                branch.setText(s9);

            }

        }
        catch(ClassNotFoundException | NumberFormatException | SQLException e)
        {

        }

    }//GEN-LAST:event_profileActionPerformed

    private void examActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examActionPerformed
        profile.setBackground(Color.red);
     
        exam.setBackground(Color.black);
       
        aboutus.setBackground(Color.red);          
        
        display.removeAll();
        studentexam p1 = null;
       try {
           p1 = new studentexam();
       } catch (SQLException ex) {
           Logger.getLogger(stupanel.class.getName()).log(Level.SEVERE, null, ex);
       }
        display.add(p1).setVisible(true);
       try {
           studentexam f = new studentexam();
       } catch (SQLException ex) {
           Logger.getLogger(stupanel.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_examActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        display.removeAll();
        result p1=new result();
        display.add(p1).setVisible(true);
        result f = new result();         // TODO add your handling code here:
    }//GEN-LAST:event_resultActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.setVisible(false);
        new loginn().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
this.setState(ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
 int resp =JOptionPane.showConfirmDialog(this,"Do you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE); 
if(resp == JOptionPane.YES_OPTION)
{
  System.exit(0);
   
}
   else if ( resp == JOptionPane.NO_OPTION)
      {
         JOptionPane.getRootFrame().dispose();
          this.setVisible(true);
      }
                    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setVisible(false);
        new loginn().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void aboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutusActionPerformed
        profile.setBackground(Color.red);
     
        exam.setBackground(Color.red);
       
        aboutus.setBackground(Color.black);
        display.removeAll();
        aboutus p1=new aboutus();
        display.add(p1).setVisible(true);
        aboutus f = new aboutus();        // TODO add your handling code here:
    }//GEN-LAST:event_aboutusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stupanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stupanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stupanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stupanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stupanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutus;
    public static javax.swing.JPanel display;
    private javax.swing.JButton exam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton profile;
    private javax.swing.JButton result;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
